on: [push]

jobs:
  build-and-deploy-aws:

    runs-on: ubuntu-latest

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    env:
      SAM_CLI_TELEMETRY: 0
      AWS_SAM_STACK_NAME: sam-cfn

    steps:
    - uses: actions/checkout@v1
    - run: sam build
    - run: pip install -r tests/requirements.txt --user
    - run: python -m pytest tests/unit -v
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{secrets.AWS_ROLE}}
        role-duration-seconds: 900
        aws-region: ap-southeast-2
    - run: aws sts get-caller-identity
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --resolve-s3 --stack-name ${AWS_SAM_STACK_NAME} --capabilities CAPABILITY_IAM
    - run: python -m pytest tests/integration -v 
