name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: SAM build
      run: sam build
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{secret.AWS_ROLE}}
        role-duration-seconds: 900
        aws-region: ap-southeast-2
    - name: SAM deploy
      run: aws sts get-caller-identity