on: [push]

jobs:
  build-and-deploy-aws:

    runs-on: ubuntu-latest

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
    - uses: actions/checkout@v1
    - run: sam build
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{secrets.AWS_ROLE}}
        role-duration-seconds: 900
        aws-region: ap-southeast-2
    - run: aws sts get-caller-identity
  